[package]
name = "kite-passenger"
version = "0.1.0"
edition = "2021"
description = "Protocol definitions for communication between Kite services"

[dependencies]
prost = "0.10.4"
wee_alloc = "0.4.5"

[features]
default = ["proto_full"]
# @@protoc_insertion_point(features)